spring.application.name=web-nutri-api
server.port=${SERVER_PORT:8080}

# ===============================
# DATASOURCE - PostgreSQL / Supabase
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/web_nutri}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# ERROS
# ===============================
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never