spring.application.name=web-nutri-api
server.port=${SERVER_PORT:8080}

# ===============================
# DATASOURCE - PostgreSQL / Supabase
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yhilsklzvxkbxmvdojpf
spring.datasource.password=abJuyEBW1Q2zS4jc
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# FRONTEND REACT
# ===============================
app.frontend.url=http://localhost:5173
app.frontend.reset-password-path=/redefinir-senha

# ===============================
# SECURITY / SESSÃO
# ===============================
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=30m

# ===============================
# PASSWORD RESET
# ===============================
app.security.password-reset.expiration-minutes=30

# ===============================
# EMAIL / SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=EMAIL_DE_ENVIO
spring.mail.password=SENHA_DE_APP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.from=EMAIL_DE_ENVIO

# ===============================
# ERROS
# ===============================
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never